### ISSUE TITLE
Chatterbot or NLTK

### ISSUE THREAD

**Issue by akashbagchi** [akashbagchi/Sem6-2022-SPII-Mental-Health-Chatbot-using-Python#1]
Is this version still using chatterbot or is it using the NLTK/TensorFlow model from my back-end?
Because it doesn't seem runnable without the chatterbot package
(Haven't read through the entire code yet)

**Comment by pranjalpadakannaya** [comment]
It is using the NLTK/Tensorflow backend so it shouldn't really be needing chatterbot since basicChatbot.py is the only file referenced in app.py
All components of the previous chatterbot model have been removed.
